### ISSUE TITLE
System Flow 작성

### ISSUE THREAD

**Issue by devejs** [SeongNamYouthTeamE/RaspiCam#12]

**Comment by MyungjinKang** [comment]
![RaspiCam구조](https://user-images.githubusercontent.com/72066510/99408398-8a94a380-2933-11eb-8fbc-11b89bea964a.PNG)

**Comment by MyungjinKang** [comment]
![RaspiCam구조](https://user-images.githubusercontent.com/72066510/99409904-38ed1880-2935-11eb-901b-31cd790bd774.PNG)

**Comment by MyungjinKang** [comment]
![Uploading 서비스흐름도.PNG…]()

**Comment by MyungjinKang** [comment]
![서비스흐름도](https://user-images.githubusercontent.com/72066510/99410012-515d3300-2935-11eb-87aa-b3791ce020df.PNG)
