### ISSUE TITLE
웹 서버 이미지 수신

### ISSUE THREAD

**Issue by devejs** [SeongNamYouthTeamE/RaspiCam#3]

**Comment by wooogy-dev** [comment]
현재 클라우드 서비스로 linux ubuntu 16.04 서버 대여 후(무료 서버) 공인 ip 발급하여 django 웹서버 외부에서 접속 성공했습니다.
-20201021-

**Comment by wooogy-dev** [comment]
클라이언트에서 송신한 이미지를 웹서버로 수신하여 특정 폴더에 test1, test2, test3 등으로 넘버링하여 저장하는 것 구현 완료
- 서버에는 구현 안 해 놓음
